from .service import Service
from bs4 import BeautifulSoup
from ..models.hours import Shift,Hours

class StoreService(Service):

	def __init__(self,session_manager,domain):

		super().__init__(session_manager,domain) 

	def _set_service_routes(self,domain):

		self.panel_url = domain.rstrip('/') + "/panel/company/setting"
		self.edit_url = domain.rstrip('/') + "/util/company/savedata"

	def edit(self,
			name: str,
			link: str,
			phone_number: str,
			receive_order_whatsapp: str = "0",
			document_cnpj: str = "",
			date_timezone: str = "America/Sao_Paulo",
			tags: str = "",
			switch_layer_fade: str = "1",
			switch_whatsapp_button: str = "0",
			switch_schedule_order: str = "0",
			switch_coin: str = "0",
			switch_charge_per_order: str = "1",
			coin_rate: str = "0.00",
			switch_img_item: str = "1",
			show_item_hide_pdv: str = "0",
			switch_keep_store_open: str = "0",
			state: str = "",
			city: str = "",
			street: str = "",
			district: str = "",
			number: str = "",
			complement: str = "",
			zip_code: str = "",
			switch_delivery: str = "0",
			switch_withdrawal: str = "1",
			switch_table: str = "0",
			switch_salon_service: str = "0",
			switch_home_service: str = "0",
			switch_deliveryman_choose: str = "0",
			deliveryman_choose_type: str = "0",
			price_order_min: str = "0.00",
			template_color_menu: str = "#680000",
			template_color_menu_text: str = "#ffffff",
			template_color_footer: str = "#680000",
			template_color_footer_text: str = "#ffffff",
			template_background_color: str = "#ececec",
			template_default_layout: str = "1",
			switch_sm_facebook: str = "0",
			profile_sm_facebook: str = "",
			switch_sm_instagram: str = "0",
			profile_sm_instagram: str = "",
			switch_sm_youtube: str = "0",
			profile_sm_youtube: str = "",
			switch_sm_google_maps: str = "0",
			profile_sm_google_maps: str = "",
			switch_sm_external_link: str = "0",
			profile_sm_external_link: str = "",
			switch_money: str = "1",
			switch_card: str = "0",
			switch_mp: str = "0",
			switch_pix: str = "0",
			switch_pagseguro: str = "0",
			switch_online: str = "0",
			pix_client_id: str = "",
			pix_client_secret: str = "",
			pix_key: str = "",
			pix_type: str = "0",
			pix_key_static: str = "",
			pix_name: str = "",
			pix_key_type: str = "",
			estimated_delivery_time: str = "0",
			estimated_withdrawal_time: str = "0",
			estimated_salon_service_time: str = "0",
			estimated_home_service_time: str = "0",
			message_api_switch: str = "0",
			message_api_type: str = "1",
			message_api_url: str = "",
			switch_pixel_facebook: str = "0",
			switch_alphabetical_order: str = "0",
			switch_widget_ifood: str = "0",
			widget_merchant_id_ifood: str = "",
			switch_plugnotas: str = "0",
			plugnotas_api_key: str = "",
			plugnotas_cpfcnpj: str = "",
			plugnotas_taxes: dict = None,
			switch_focusnfe: str = "0",
			focusnfe_token: str = "",
			focusnfe_cnpj: str = "",
			focusnfe_icms_origem: str = "0",
			focusnfe_icms_situacao_tributaria: str = "102",
			show_category_limit: str = "10",
			show_item_limit: str = "5",
			custom_status_messages_accepted: str = "Seu pedido foi aceito!",
			custom_status_messages_preparing: str = "Seu pedido está sendo preparado!",
			custom_status_messages_canceled: str = "Seu pedido foi cancelado!",
			custom_status_messages_ready_0: str = "Seu pedido está pronto e logo será entregue!",
			custom_status_messages_ready_1: str = "Seu pedido está pronto para ser retirado!",
			custom_status_messages_ready_2: str = "Seu pedido será levado na sua mesa!",
			custom_status_messages_delivering: str = "Seu pedido saiu para entrega!",
			custom_status_messages_delivered: str = "Seu pedido foi entregue!",
			custom_messages_api_notify_inactive_customers: str = "",
			segments: str = "0",
			hours: str = "",
			img_form: str = "1",
			switch_img_form_item: str = "0",
	    ):

		csrf = self.get_csrf(self.panel_url)
		if not csrf:
			return {"error": "CSRF token not found"}

		# plugnotas default structure
		if plugnotas_taxes is None:
			plugnotas_taxes = {
				"icms": {
					"origem": "0",
					"cst": "00",
					"baseCalculo": {"modalidadeDeterminacao": 0, "valor": 0},
					"aliquota": 0,
					"valor": 0,
				},
					"pis": {
					"cst": "99",
					"baseCalculo": {"valor": 0, "quantidade": 0},
					"aliquota": 0,
					"valor": 0,
				},
					"cofins": {
					"cst": "07",
					"baseCalculo": {"valor": 0},
					"aliquota": 0,
					"valor": 0,
				},
			}

		if len(hours) == 0:
			hours = Hours([Shift([(True, "08:00", "12:00") for _ in range(7)]), Shift(), Shift()])

		data = {
			"action": "saveData",
			"name": name,
			"link": link,
			"phone_number": phone_number,
			"receive_order_whatsapp": receive_order_whatsapp,
			"document_cnpj": document_cnpj,
			"date_timezone": date_timezone,
			"tags": tags,
			"switch_layer_fade": switch_layer_fade,
			"switch_whatsapp_button": switch_whatsapp_button,
			"switch_schedule_order": switch_schedule_order,
			"switch_coin": switch_coin,
			"switch_charge_per_order": switch_charge_per_order,
			"coin_rate": coin_rate,
			"switch_img_item": switch_img_item,
			"show_item_hide_pdv": show_item_hide_pdv,
			"switch_keep_store_open": switch_keep_store_open,
			"state": state,
			"city": city,
			"street": street,
			"district": district,
			"number": number,
			"complement": complement,
			"zip_code": zip_code,
			"switch_delivery": switch_delivery,
			"switch_withdrawal": switch_withdrawal,
			"switch_table": switch_table,
			"switch_salon_service": switch_salon_service,
			"switch_home_service": switch_home_service,
			"switch_deliveryman_choose": switch_deliveryman_choose,
			"deliveryman_choose_type": deliveryman_choose_type,
			"price_order_min": price_order_min,
			"template_color_menu": template_color_menu,
			"template_color_menu_text": template_color_menu_text,
			"template_color_footer": template_color_footer,
			"template_color_footer_text": template_color_footer_text,
			"template_background_color": template_background_color,
			"template_default_layout": template_default_layout,
			"switch_sm_facebook": switch_sm_facebook,
			"profile_sm_facebook": profile_sm_facebook,
			"switch_sm_instagram": switch_sm_instagram,
			"profile_sm_instagram": profile_sm_instagram,
			"switch_sm_youtube": switch_sm_youtube,
			"profile_sm_youtube": profile_sm_youtube,
			"switch_sm_google_maps": switch_sm_google_maps,
			"profile_sm_google_maps": profile_sm_google_maps,
			"switch_sm_external_link": switch_sm_external_link,
			"profile_sm_external_link": profile_sm_external_link,
			"switch_money": switch_money,
			"switch_card": switch_card,
			"switch_mp": switch_mp,
			"switch_pix": switch_pix,
			"switch_pagseguro": switch_pagseguro,
			"switch_online": switch_online,
			"pix_client_id": pix_client_id,
			"pix_client_secret": pix_client_secret,
			"pix_key": pix_key,
			"pix_type": pix_type,
			"pix_key_static": pix_key_static,
			"pix_name": pix_name,
			"pix_key_type": pix_key_type,
			"estimated_delivery_time": estimated_delivery_time,
			"estimated_withdrawal_time": estimated_withdrawal_time,
			"estimated_salon_service_time": estimated_salon_service_time,
			"estimated_home_service_time": estimated_home_service_time,
			"message_api_switch": message_api_switch,
			"message_api_type": message_api_type,
			"message_api_url": message_api_url,
			"switch_pixel_facebook": switch_pixel_facebook,
			"switch_alphabetical_order": switch_alphabetical_order,
			"switch_widget_ifood": switch_widget_ifood,
			"widget_merchant_id_ifood": widget_merchant_id_ifood,
			"switch_plugnotas": switch_plugnotas,
			"plugnotas_api_key": plugnotas_api_key,
			"plugnotas_cpfcnpj": plugnotas_cpfcnpj,
			"plugnotas_taxes": str(plugnotas_taxes),
			"switch_focusnfe": switch_focusnfe,
			"focusnfe_token": focusnfe_token,
			"focusnfe_cnpj": focusnfe_cnpj,
			"focusnfe_icms_origem": focusnfe_icms_origem,
			"focusnfe_icms_situacao_tributaria": focusnfe_icms_situacao_tributaria,
			"show_category_limit": show_category_limit,
			"show_item_limit": show_item_limit,
			"custom_status_messages_accepted": custom_status_messages_accepted,
			"custom_status_messages_preparing": custom_status_messages_preparing,
			"custom_status_messages_canceled": custom_status_messages_canceled,
			"custom_status_messages_ready_0": custom_status_messages_ready_0,
			"custom_status_messages_ready_1": custom_status_messages_ready_1,
			"custom_status_messages_ready_2": custom_status_messages_ready_2,
			"custom_status_messages_delivering": custom_status_messages_delivering,
			"custom_status_messages_delivered": custom_status_messages_delivered,
			"custom_messages_api_notify_inactive_customers": custom_messages_api_notify_inactive_customers,
			"segments": segments,
			"hours": str(hours),
			"img_form": img_form,
			"switch_img_form_item": switch_img_form_item,
		}

		headers = {"X-CSRF-TOKEN": csrf}
		response = self.session.post(self.edit_url, data=data,headers = headers,timeout=15)
		response.raise_for_status()
		try:
			return response.json()
		except Exception:
			return {'raw': response.text}
    
	'''
	def edit(self,name,link,phone_number,document_cnpj,state,city,district,number,street,complement,zip_code,receive_order_whatsapp = False,date_timezone="America/Sao_Paulo",tags="",
			switch_layer_fade = True,switch_whatsapp_button=False,switch_schedule_order = False,switch_coin=False,
			switch_charge_per_order=True,coin_rate = 0.00,switch_img_item = True,show_item_hide_pdv = False,
			switch_keep_store_open = False,switch_delivery = False,switch_withdrawal = True,switch_table = False,
			switch_salon_service = False,switch_home_service = False,switch_deliveryman_choose = False,deliveryman_choose_type=False,
			price_order_min = "0.00",template_color_menu = "#680000",template_color_menu_text = "#ffffff",template_color_footer = "#680000",
			template_color_footer_text="#ffffff",template_background_color="#ececec",template_default_layout=True,switch_sm_facebook=False,
			profile_sm_facebook="",switch_sm_instagram=False,profile_sm_instagram= "",switch_sm_youtube=False,profile_sm_youtube="",switch_sm_google_maps=False,
			profile_sm_google_maps="",switch_sm_external_link=False,profile_sm_external_link="",switch_money=True,switch_card=False,switch_mp=False,):

		csrf = self.get_csrf(self.panel_url)
		if not csrf:
			return {"error": "CSRF token not found"}

		data = {
			"action":'saveData',
			"name": name,
			"link":link,
			"phone_number":phone_number,
			"receive_order_whatsapp": "1" if receive_order_whatsapp else "0",
			"document_cnpj": document_cnpj,
			"date_timezone":date_timezone,
			"tags":tags,
			"switch_layer_fade": "1" if switch_layer_fade else "0",
			"switch_whatsapp_button": "1" if switch_whatsapp_button else "0",
			"switch_schedule_order": "1" if switch_schedule_order else "0",
			"switch_coin": "1" if switch_coin else "0",
			"switch_charge_per_order": "1" if switch_charge_per_order else "0",
			"coin_rate": str(coin_rate),
			"switch_img_item": "1" if switch_img_item else "0",
			"show_item_hide_pdv": "1" if show_item_hide_pdv else "0",
			"switch_keep_store_open": "1" if switch_keep_store_open else "0",
			"state":state,
			"city":city,
			"street":street,
			"district":district,
			"number":number,
			"complement":complement,
			"zip_code":zip_code,
			"switch_delivery": "1" if switch_delivery else "0",
			"switch_withdrawal": "1" if switch_withdrawal else "0",
			"switch_table": "1" if switch_table else "0",
			"switch_salon_service": "1" if switch_salon_service else "0",
			"switch_home_service": "1" if switch_home_service else "0",
			"switch_deliveryman_choose": "1" if switch_deliveryman_choose else "0",
			"deliveryman_choose_type": "1" if deliveryman_choose_type else "0",
			"price_order_min":price_order_min,
			"template_color_menu":template_color_menu,
			"template_color_menu_text":template_color_menu,
			"template_color_footer":template_color_footer,
			"template_color_footer_text":template_color_footer_text,
			"template_background_color":template_background_color,
			"template_default_layout":"1" if template_default_layout else "0",
			"switch_sm_facebook":"1" if switch_sm_facebook else "0",
			"profile_sm_facebook":profile_sm_facebook,
			"switch_sm_instagram":"1" if switch_sm_instagram else "0",
			"profile_sm_instagram": profile_sm_instagram,
			"switch_sm_youtube":"1" if switch_sm_youtube else "0",
			"profile_sm_youtube":profile_sm_youtube,
			"switch_sm_google_maps":"1" if switch_sm_google_maps else "0",
			"profile_sm_google_maps": profile_sm_google_maps,
			"switch_sm_external_link":"1" if switch_sm_external_link else "0",
			"profile_sm_external_link": profile_sm_external_link,
			"switch_money": "1" if switch_money else "0",
			"switch_card":"1" if switch_card else "0",
			"switch_mp":"0",
			"switch_pix":"0",
			"switch_pagseguro":"0",
			"switch_online":"0",
			"pix_client_id",
			"pix_client_secret",
			"pix_key",
			"pix_type":"0",
			"pix_key_static",
			"pix_name",
			"pix_key_type",
			"estimated_delivery_time":"0",
			"estimated_withdrawal_time":"0",
			"estimated_salon_service_time":"0",
			"estimated_home_service_time":"0",
			"message_api_switch":"0",
			"message_api_type":"1",
			"message_api_url",
			"switch_pixel_facebook":"0",
			"switch_alphabetical_order":"0",
			"switch_widget_ifood":"0",
			"widget_merchant_id_ifood",
			"switch_plugnotas":"0",
			"plugnotas_api_key",
			"plugnotas_cpfcnpj",
			"plugnotas_taxes":
			{
			    "icms": {
			        "origem": "0",
			        "cst": "00",
			        "baseCalculo": {
			            "modalidadeDeterminacao": 0,
			            "valor": 0
			        },
			        "aliquota": 0,
			        "valor": 0
			    },
			    "pis": {
			        "cst": "99",
			        "baseCalculo": {
			            "valor": 0,
			            "quantidade": 0
			        },
			        "aliquota": 0,
			        "valor": 0
			    },
			    "cofins": {
			        "cst": "07",
			        "baseCalculo": {
			            "valor": 0
			        },
			        "aliquota": 0,
			        "valor": 0
			    }
			}
			"switch_focusnfe":"0",
			"focusnfe_token",
			"focusnfe_cnpj",
			"focusnfe_icms_origem":"0",
			"focusnfe_icms_situacao_tributaria":"102",
			"show_category_limit":"10",
			"show_item_limit":"5",
			"custom_status_messages_accepted":"Seu pedido foi aceito!",
			"custom_status_messages_preparing":"Seu pedido está sendo preparado!",
			"custom_status_messages_canceled":"Seu pedido foi cancelado!",
			"custom_status_messages_ready_0":"Seu pedido está pronto e logo será entregue!",
			"custom_status_messages_ready_1":"Seu pedido está pronto para ser retirado!",
			"custom_status_messages_ready_2":"Seu pedido será levado na sua mesa!",
			"custom_status_messages_delivering":"Seu pedido saiu para entrega!",
			"custom_status_messages_delivered":"Seu pedido foi entregue!",
			"custom_messages_api_notify_inactive_customers":"Ei, *${customer_name}*! 👋\n\nSentimos sua falta por aqui! Faz tempo que não saboreia nossos produtos 🍔🍕\nQue tal matar a saudade hoje mesmo? 😋\n\nClique no link abaixo e faça seu pedido agora:\n${company_link}",
			"segments":"0",
			"hours":"[{"switch_sun":1,"sun_i":"08:00","sun_u":"12:00","switch_mon":1,"mon_i":"08:00","mon_u":"12:00","switch_tue":1,"tue_i":"08:00","tue_u":"12:00","switch_wed":1,"wed_i":"08:00","wed_u":"12:00","switch_thu":1,"thu_i":"08:00","thu_u":"12:00","switch_fri":1,"fri_i":"08:00","fri_u":"12:00","switch_sat":1,"sat_i":"08:00","sat_u":"12:00"},{"switch_sun":1,"sun_i":"14:00","sun_u":"18:00","switch_mon":1,"mon_i":"14:00","mon_u":"18:00","switch_tue":1,"tue_i":"14:00","tue_u":"18:00","switch_wed":1,"wed_i":"14:00","wed_u":"18:00","switch_thu":1,"thu_i":"14:00","thu_u":"18:00","switch_fri":1,"fri_i":"14:00","fri_u":"18:00","switch_sat":1,"sat_i":"14:00","sat_u":"18:00"},{"switch_sun":0,"sun_i":"00:00:00","sun_u":"00:00:00","switch_mon":0,"mon_i":"00:00","mon_u":"00:00","switch_tue":0,"tue_i":"00:00","tue_u":"00:00","switch_wed":0,"wed_i":"00:00:00","wed_u":"00:00:00","switch_thu":0,"thu_i":"00:00:00","thu_u":"00:00:00","switch_fri":0,"fri_i":"00:00","fri_u":"00:00","switch_sat":0,"sat_i":"00:00:00","sat_u":"00:00:00"}]",
			"img_form":"1",
			"switch_img_form_item":"0",
			"_token": csrf,
		}

		response = self.session.post(self.deliveryMan_url, data=data, timeout=15)
		response.raise_for_status()
		try:
			return response.json()
		except Exception:
			return {'raw': response.text}

		return
		'''